CREATE DATABASE likes_app;
USE likes_app;
CREATE TABLE users(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100),
email VARCHAR(100)
);
CREATE TABLE posts(
id INT AUTO_INCREMENT PRIMARY KEY,
content TEXT,
created_at DATETIME,
user_id INT,
FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE TABLE likes(
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT,
post_id INT,
FOREIGN KEY (user_id) REFERENCES users(id),
FOREIGN KEY (post_id) REFERENCES posts(id)
);