# Generated by Django 6.0.5 on 2026-06-12 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='desc',
        ),
    ]
